### ISSUE TITLE
Error loading extenstion

### ISSUE THREAD

**Issue by max194** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#14]
After following all steps, when trying to load "burpWhatsapp.py" in burp I get an error:

`Traceback (most recent call last):
  File "C:\Python27\Lib\site.py", line 539, in <module>
    main()
  File "C:\Python27\Lib\site.py", line 521, in main
    known_paths = addusersitepackages(known_paths)
  File "C:\Python27\Lib\site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "C:\Python27\Lib\site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "C:\Python27\Lib\site.py", line 231, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "C:\Python27\Lib\sysconfig.py", line 525, in get_config_var
    return get_config_vars().get(name)
  File "C:\Python27\Lib\sysconfig.py", line 475, in get_config_vars
    _init_non_posix(_CONFIG_VARS)
  File "C:\Python27\Lib\sysconfig.py", line 373, in _init_non_posix
    vars['BINDIR'] = os.path.dirname(_safe_realpath(sys.executable))
  File "C:\Python27\Lib\sysconfig.py", line 99, in _safe_realpath
    return realpath(path)
  File "C:\Python27\Lib\sysconfig.py", line 99, in _safe_realpath
    return realpath(path)
  File "C:\Python27\Lib\ntpath.py", line 474, in abspath
    if not isabs(path):
  File "C:\Python27\Lib\ntpath.py", line 58, in isabs
    s = splitdrive(s)[1]
  File "C:\Python27\Lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyObject.__len__(PyObject.java:650)
	at org.python.core.__builtin__.len(__builtin__.java:729)
	at org.python.core.BuiltinFunctions.__call__(__builtin__.java:64)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at ntpath$py.splitdrive$4(C:\Python27\Lib\ntpath.py:135)
	at ntpath$py.call_function(C:\Python27\Lib\ntpath.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at ntpath$py.isabs$2(C:\Python27\Lib\ntpath.py:59)
	at ntpath$py.call_function(C:\Python27\Lib\ntpath.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at ntpath$py.abspath$18(C:\Python27\Lib\ntpath.py:480)
	at ntpath$py.call_function(C:\Python27\Lib\ntpath.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at sysconfig$py._safe_realpath$1(C:\Python27\Lib\sysconfig.py:101)
	at sysconfig$py.call_function(C:\Python27\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at sysconfig$py._init_non_posix$13(C:\Python27\Lib\sysconfig.py:373)
	at sysconfig$py.call_function(C:\Python27\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at sysconfig$py.get_config_vars$20(C:\Python27\Lib\sysconfig.py:517)
	at sysconfig$py.call_function(C:\Python27\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:118)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at sysconfig$py.get_config_var$21(C:\Python27\Lib\sysconfig.py:525)
	at sysconfig$py.call_function(C:\Python27\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at site$py.getuserbase$8(C:\Python27\Lib\site.py:232)
	at site$py.call_function(C:\Python27\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at site$py.getusersitepackages$9(C:\Python27\Lib\site.py:256)
	at site$py.call_function(C:\Python27\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at site$py.addusersitepackages$10(C:\Python27\Lib\site.py:270)
	at site$py.call_function(C:\Python27\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at site$py.main$33(C:\Python27\Lib\site.py:537)
	at site$py.call_function(C:\Python27\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at site$py.f$0(C:\Python27\Lib\site.py:591)
	at site$py.call_function(C:\Python27\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:861)
	at org.python.core.imp.load(imp.java:716)
	at org.python.core.Py.importSiteIfSelected(Py.java:1558)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at burp.owb.<init>(Unknown Source)
	at burp.s5c.a(Unknown Source)
	at burp.zfb.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

How can I fix this?

**Comment by romanzaikin** [comment]
which OS do you use? and make sure you have the latest python, burp, jython

**Comment by max194** [comment]
I'm using Windows 10 64bit

**Comment by max194** [comment]
Fixed it by redownloading jython
